### ISSUE TITLE
value transformation do not work

### ISSUE THREAD

**Issue by ahmedaall** [opsdis/aci-exporter#32]
**Describe the bug**
value_transform do not work. It always display 0 as id no matter the value of the operstatus

``` infra_node_psu:
    class_name: eqptPsu
    metrics:
      - name: infra_node_psu
        value_name: X
        type: "gauge"
        help: "Returns the info of the node psu states"
        unit: "info"
        value_calculation: "1"
    value_transform:
        'unknown':            0
        'ok':                 1
        'fail':               2
        'absent':             3
        'shut':               4
        'mismatch':           5

**Comment by thenodon** [comment]
Hi @ahmedaall, 
In the future do not send screenshots, send the real or part of the config file as yaml.
The obvious reason it is not working is that your configuration is wrong. `value_transform` is part of `metrics`. Please checkout https://github.com/opsdis/aci-exporter/blob/master/example-config.yaml and make sure your indentation is correct.
Since you do not do any value_calculation you do not need to specify it. 
Hope that solves you problem

**Comment by ahmedaall** [comment]
Hi @thenodon 
I will take this file as a reference for the futur ! It works now with the good indentation.
Thx !

**Comment by thenodon** [comment]
Great to hear @ahmedaall 
Just some additional information that can be good to know. In the current implementation of aci-exporter 0 is the default value if a correct float can not be returned. It is visible  in the log as a warning.

**Comment by thenodon** [comment]
Closed
